name = "skillrank"
workers_dev = true

main = "build/worker/shim.mjs"
compatibility_date = "2022-06-09"

[vars]
WORKERS_RS_VERSION = "0.0.11"

[build]
command = "worker-build --release"

[durable_objects]
bindings = [{name = "RANKINGS", class_name = "Rankings"}]

[[kv_namespaces]]
binding = "SKILLRANK_IDS"
id = "35a3b32e5e44468fa99c5b03b388bfdd"

[[migrations]]
tag = "v1"
new_classes = ["Rankings"]
